export const VACCINEDATA_TO_GET_LOADING = "VACCINEDATA_TO_GET_LOADING";
export const VACCINEDATA_GET_SUCCESS = "VACCINEDATA_GET_SUCCESS ";
export const VACCINEDATA_GET_FAILURE = "VACCINEDATA_GET_FAILURE ";
export const VACCINATION_DONE = "VACCINATION_DONE";
